nelmio_security:
    csp:
        enabled: true
        enforce:
            # default-src:
            #     - 'self'
            #     - 'unsafe-inline'
            script-src:
                - 'self'
                - 'unsafe-inline'
            # style-src:
            #     - 'self'
            #     - 'unsafe-inline'
            # font-src:
            #     - 'self'
            #     - 'unsafe-inline'
            # object-src:
            #     - 'self'
            #     - 'unsafe-inline'
